### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mli** [dmlc/difacto#5]
- [ ] logit / fm loss: `src/loss/`
- [ ] minibatch sgd: `src/sgd/`
- [ ] block coordinate descent: `src/bcd`
- [ ] l-bfgs: `src/lbfgs`
- [ ] distributed by ps-lite: `src/store/store_dist.h`
- [ ] use disk as data cache: `class DataStoreDisk`
